apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustom-hello
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: hello-kustom
    repoURL: 'https://github.com/rmtodd618/hello.git'
    targetRevision: v3
