apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nginx-helloworld
        image: rmtodd618/helloworld:v2.0
        ports:
        - containerPort: 80