replicaCount: 3

image:
  repository: rmtodd618/helloworld
  pullPolicy: IfNotPresent
  tag: "v2.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
