replicaCount: 3
deployment:
  enabled: true
rollout: 
  enabled: true
image:
  repository: rmtodd618/helloworld
  pullPolicy: IfNotPresent
  tag: "v1.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
