apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-controller
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/rmtodd618/hello.git'
    targetRevision: v3
    helm:
      valueFiles:
        - values.yaml
    path: rollout-controller/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=orphan
    - PruneLast=true
